# Generated by Django 4.2.3 on 2023-07-26 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_category_auctionlisting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
