# Generated by Django 4.2.3 on 2023-07-26 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_category_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="current_bid",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="auctionlisting",
            name="starting_bid",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
