# Generated by Django 4.2.3 on 2023-07-27 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_rename_auctionlisting_listing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="categoryName",
        ),
    ]
